# theme = "solarized-dark"
theme = "slick"
# theme = "plain"

icons = "awesome"

# [[block]]
# block = "disk_space"
# path = "/"
# alias = ""
# info_type = "available"
# unit = "GB"
# interval = 20
# warning = 20.0
# alert = 1.0

# [[block]]
# block = "focused_window"
# max_width = 21

[[block]]
block = "disk_space"
path = "/"
alias = "⛁"
# info_type = "free"
info_type = "available"
# show_percentage = true
unit = "GB"
interval = 20
warning = 1.0
alert = 1.0

# [[block]]
# block = "memory"
# display_type = "memory"
# format_mem = "{Mup}%"
# format_swap = "{SUp}%"

# [[block]]
# block = "cpu"
# interval = 1

[[block]]
block = "cpu"
info = 40
warning = 50
critical = 80
interval = 1
format = "{utilization}%"

# [[block]]
# block = "custom"
# cycle = ["echo ON", "echo OFF"]
# on_click = "<command>"
# interval = 1

# [[block]]
# block = "load"
# interval = 1
# format = "{1m}"





# [[block]]
# block = "net"
# device = "wlp3s0"
# ssid = true
# signal_strength = true
# # ip = true
# # speed_up = false
# # graph_up = true
# graph_down = true
# interval = 5

# [[block]]
# block = "speedtest"
# bytes = true
# interval = 1800

[[block]]
block = "sound"
# alias ="🔊"

[[block]]
block = "battery"
# show = "both"
device = "/sys/class/power_supply/BAT1/"
interval = 10
format = "{percentage}%"

[[block]]
block = "time"
interval = 60
format = "%a %h %d %I:%M"

# [[block]]
# block = "xrandr"
# icons = true
# resolution = true
# interval = 2
