[theme]
name = "slick"
# name = "solarized-dark"
# name = "plain"

[theme.overrides]
# idle_bg      = "#4a76ce"
idle_fg      = "#AAAAAA"
info_bg      = "#4a76ce"
info_fg      = "#000000"
good_bg      = "#4a76ce"
good_fg      = "#FFFFFF"
# warning_bg   = " "
# warning_fg   = " "
# critical_bg  = " "
# critical_fg  = " "
# separator    = "<"
# separator_bg = "#FFFFFF"
# separator_fg = "#000000"

[icons]
name            = "awesome"

[icons.overrides]
bat                = " | | "
# bat_full           = " "
bat_full           = " 🗸"
bat_charging       = " 🔌 "
bat_discharging    = "⚡"
# volume_muted       = " 🔇 "
volume_full        = " 🔊 "
volume_half        = " 🔉 "
volume_empty       = " 🔇 "
cpu                = " 💻 "
time               = ""
music              = " 💿 "
# music              = " 🎵 "
music_play         = "⏵"
music_pause        = "⏸"
music_next         = "⧐ "
music_prev         = "⧏"
backlight_empty    = " 🌑 "
backlight_partial1 = " 🌘 "
backlight_partial2 = " 🌗 "
backlight_partial3 = " 🌖 "
backlight_full     = " 🌕 "
# cogs            = " "
# memory_mem      = " "
# memory_swap     = " "
# update          = " "
# toggle_off      = " "
# toggle_on       = " "
# thermometer     = " "
# xrandr          = " "

# [[block]]
# block              = "maildir"
# interval           = 60
# inboxes            = ["/home/esk/mail/local", "/home/esk/mail/gmail/Inbox"]
# threshold_warning  = 1
# threshold_critical = 10
# display_type       = "new"

# [[block]]
# block             = "mail"
# interval          = 60
# inboxes           = ["/home/user/mail/local", "/home/user/mail/gmail/Inbox"]
# threshold_warning = 1
# threshold_warning = 10

# [theme]
# name        = "slick"
# [theme.overrides]
# idle_bg     = "#303030"
# idle_fg     = "#C6C6C6"
# info_bg     = "#A83334"
# info_fg     = "#C6C6C6"
# good_fg     = "#C6C6C6"
# warning_fg  = "#C6C6C6"
# critical_fg = "#C6C6C6"
# [icons]
# name = "awesome"

[[block]]
block     = "music"
# player    = "spotify"
marquee   = true
marquee_interval = 3
max_width = 10
buttons   = ["prev", "play", "next"]
on_collapsed_click = "vlc"

# [[block]]
# block = "music"
# player = "spotify"
# buttons = ["play", "next"]

# [[block]]
# block     = "disk_space"
# path      = "/"
# alias     = ""
# info_type = "available"
# unit      = "GB"
# interval  = 20
# warning   = 20.0
# alert     = 1.0

# [[block]]
# block = "focused_window"
# max_width = 10

[[block]]
block     = "disk_space"
path      = "/"
alias     = "⛁"
# info_type = "free"
info_type = "available"
# show_percentage = true
unit      = "GB"
interval  = 20
warning   = 1.0
alert     = 1.0

# [[block]]
# block        = "memory"
# display_type = "memory"
# format_mem   = "{Mup}%"
# format_swap  = "{SUp}%"

# [[block]]
# block = "cpu"
# interval = 1

# [[block]]
# block           = "net"
# device          = "wlp3s0"
# ssid            = false
# signal_strength = true
# ip              = true
# speed_up        = true
# speed_down      = true
# graph_down      = true
# graph_up        = true
# interval        = 3

[[block]]
block    = "cpu"
info     = 60
warning  = 70
critical = 80
interval = 1
format   = "{utilization}%"

# [[block]]
# block    = "load"
# interval = 1
# format   = "{1m}"

# [[block]]
# block    = "speedtest"
# bytes    = true
# interval = 1000

[[block]]
block    = "sound"
step_width = 1
# driver = "auto"
on_click = "pactl set-sink-mute @DEFAULT_SINK@ toggle"
show_volume_when_muted = true

# [[block]]
# block = "backlight"
# device = "intel_backlight"
# # device = "/sys/class/backlight/intel_backlight/"

[[block]]
block    = "battery"
# show = "both"
device   = "/sys/class/power_supply/BAT2/"
# device = "/sys/class/power_supply/BAT1/"
interval = 10
format   = "{percentage}%"

# [[block]]
# block = "uptime"

# [[block]]
# block = "bluetooth"
# mac = "34:88:5D:46:3A:C4"
# # mac = "38:DE:AD:CC:40:B5"

# [[block]]
# block = "xrandr"
# icons = true
# resolution = true
# interval = 2

[[block]]
block    = "time"
interval = 60
# format = " 🗓 %a %h-%d⏲%_I:%M %p"
format   = " 📅 %a %h-%d 🕒%_I:%M %p"

[[block]]
block    = "custom"
command  = "~/.rc/flag-script.sh"
# cycle    = ["echo ON", "echo OFF"]
# on_click = "exec code" # run vscode up on click
interval = 100

